[package]
name = "merger"
version = "0.1.0"
edition = "2021"
authors = ["Achilleas Buisman <accounts@abuisman.nl>"]
publish = false

[lib]
name = "merger"
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
rustui_merge = "0.1.6"
